image: denoland/deno:latest
# image: rustdocker/rust:stable

stages:
  - Build
  - Test
  - deploy

Cli:
  stage: Build
  script: deno task cli:build
  artifacts:
    paths:
      - bin/zzz

Http:
  stage: Build
  script: deno task http:build
  artifacts:
    paths:
      - bin/zzz-server

# Web:
#   stage: Build
#   script: deno task web:build

Tauri:
  stage: Build
  script:
    deno task tauri:build
    # - mv src\apps\zzz\interfaces\desktop\target\release

Tests: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - deno task test
    - deno task coverage

Lint:
  stage: Test
  script:
    - deno task lint
    - deno fmt --check

deploy-job:
  stage: Deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
