image: denoland/deno:latest
# image: rustdocker/rust:stable

# curl -fsSL https://deno.land/install.sh | sh
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

stages:
  - Test
  - Build
  - Deploy

Cli:
  stage: Build
  script: deno task cli:build
  artifacts:
    paths:
      - bin/zzz

Http:
  stage: Build
  script: deno task http:build
  artifacts:
    paths:
      - bin/zzz-server

# Web:
#   stage: Build
#   script: deno task web:build

# Tauri:
#   stage: Build
#   script:
#     - deno task tauri:build
# - mv src\apps\zzz\interfaces\desktop\target\release

Tests:
  stage: Test
  script:
    - deno task test
    - deno task coverage

Lint:
  stage: Test
  script:
    - deno task lint
    - deno fmt --check

DeployWeb:
  stage: Deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
