default:
  image: denoland/deno:latest

# curl -fsSL https://deno.land/install.sh | sh
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

stages:
  - Build
  - Test
  - Deploy

Cli:
  stage: Build
  script: deno task cli:build ; mv bin/zzz ./
  artifacts:
    name: zzz-cli
    paths:
      - ./zzz
    expire_in: 1 week

Http:
  stage: Build
  script: deno task http:build ; mv bin/zzz-server ./
  artifacts:
    name: zzz-server
    paths:
      - ./zzz-server
    expire_in: 1 week

Web:
  stage: Build
  script: deno task web:build
  artifacts:
    name: zzz-web
    paths:
      - ./src/apps/zzz/interfaces/web/dist
    expire_in: 1 week

Desktop:
  image: rustdocker/rust:stable
  stage: Build
  script: deno task desktop:build ; mv src/apps/zzz/interfaces/desktop/target/release/Zzz ./zzz-desktop
  artifacts:
    name: zzz-desktop
    paths:
      - ./zzz-desktop
    expire_in: 1 week

Tests:
  stage: Test
  script:
    - deno task test
    - deno task coverage

Lint:
  stage: Test
  script:
    - deno task lint
    - deno fmt --check

DeployWeb:
  stage: Deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
# https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html
